// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "antfu"
export const name = "json-discovery"
export const version = "0.1.1"
export const displayName = "JSON Discovery"
export const description = "JSON Discovery for opening .cpuprofile files in VS Code."
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey = 
  | "json-discovery.show"

/**
 * Commands map registed by `antfu.json-discovery`
 */
export const commands = {
  /**
   * Show in JSON Discovery
   * @value `json-discovery.show`
   */
  show: "json-discovery.show",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = never

export interface ConfigKeyTypeMap {
}

export interface ConfigShorthandMap {
}

export interface ConfigShorthandTypeMap {
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `antfu.json-discovery`
 */
export const configs = {
}

export interface ScopedConfigKeyTypeMap {
}

export const scopedConfigs = {
  scope: "json-discovery",
  defaults: {
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
}

export interface NestedScopedConfigs {
}

